# rustcmd C++ WebRCON tool config for RustDedicated WebSocket interface
#
# EXAMPLE: 
#
# RUST_RCON_IP=127.0.0.1
# RUST_RCON_PORT=28016
# RUST_RCON_PASSWORD=Abc123xyZ
#
# RUST_SERVICE_UNIT=/etc/systemd/system/rust_server.service
#

RUST_RCON_IP=your-RCON-IP-address
RUST_RCON_PORT=your-RCON-PORT
RUST_RCON_PASSWORD=your-RCON-passwd

RUST_SERVICE_UNIT=/PATH/TO/YOUR/rust_server.service
